name: build_mi10_series_hyperos_OneDrivePush
on:
  workflow_dispatch:
    inputs:
      STOCK_URL:
        description: "BASEROM DIRECT DOWNLOAD LINK(XIAOMI.EU or CN OFFICIAL ROM)"
        required: true
      PORT_URL:
        description: "PORTROM DIRECT DOWNLOAD LINK(XIAOMI.EU OR CN OFFICIAL ROM)"
        required: true
      PACK_TYPE:
        description: "PACKING TYPE(EXT/EROFS), EROFS BY DEFAULT"
        default: EROFS
        required: false
      ENCRYPTION:
        description: "FBE DECRYPTION OR NOT, FBE ENABLED BY DEFAULT"
        default: FALSE
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 1. DEBLOAT COMPONENTS
        run: |
          docker rmi `docker images -q` || true
          sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/sudo apt/sources.list.d || true
          sudo apt -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php* || true
          sudo apt -y autoremove --purge || true
          sudo apt -y autoclean || true
          sudo apt clean || true
      - name: 2. MAXIMIZE BUILD SPACE
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 1024
          swap-size-mb: 6144
          remove-dotnet: "true"
          temp-reserve-mb: 1024
          remove-android: "true"
          remove-haskell: "true"
      - name: 3. CHECKOUT REPOSITORY
        uses: actions/checkout@main
        with:
          ref: dev
          fetch-depth: 1
      - name: 4. PREPARE ENVIRONMENT
        run: |
          sudo apt install python3 python3-pip aria2 zip p7zip-full tar zipalign zstd android-sdk-libsparse-utils xmlstarlet coreutils
          sudo apt --fix-broken install
          sudo apt update --fix-missing
          pip3 install --upgrade pip
          curl https://rclone.org/install.sh | sudo bash
          mkdir -p ~/.config/rclone/
          echo "${{ secrets.RCLONE_TOKEN }}" > token.txt
      - name: 5. START PORTING
        run: |
          cd "$GITHUB_WORKSPACE"
          mkdir tmp
          rclone sync -P hmadv:/ROM_FILES/ tmp/
          zipfiles=$(find tmp -name "*.zip")
          for file in $zipfiles; do
            echo "Unzipping $file to devices folder" 
            unzip -o $file -d devices
          done
          if [[ ${{ github.event.inputs.PACK_TYPE }} == "EROFS" ]]; then
              sed -i "s/repack_with_ext4=true/repack_with_ext4=false/" bin/port_config
          fi

          if [[ ${{ github.event.inputs.ENCRYPTION }} == "TRUE" ]]; then
              sed -i "s/remove_data_encryption=false/remove_data_encryption=true/" bin/port_config
          fi
          sudo python3 -m pip install lxml rich
          sudo python3 "$GITHUB_WORKSPACE"/port.py ${{ github.event.inputs.STOCK_URL }} ${{ github.event.inputs.PORT_URL }}
      - name: 6. PREPARE UPLOADING
        run: |
          ROM_FILE=$(basename $(find "$GITHUB_WORKSPACE"/out -name "*.zip"))
          echo "ROM_FILE=$ROM_FILE" >>$GITHUB_ENV
          OS_VERSION=$(echo $ROM_FILE | cut -d "_" -f3)
          echo "OS_VERSION=$OS_VERSION" >>$GITHUB_ENV
          mkdir -p "$GITHUB_WORKSPACE"/GithubRelease
          cd "$GITHUB_WORKSPACE"/GithubRelease
          sudo split -b 1536M -d "$GITHUB_WORKSPACE"/out/$ROM_FILE $ROM_FILE
          ls -al "$GITHUB_WORKSPACE"/GithubRelease/
      - name: 7. PUSH ROM TO ONEDRIVE
        run: |
            rclone sync -P "$GITHUB_WORKSPACE"/out/${{ env.ROM_FILE }} hmadv:/ROM/Test
     
